language: clojure
before_install: cd clojure
after_script: CLOVERAGE_VERSION='1.0.5' lein cloverage --coveralls && curl -F 'json_file=@target/coverage/coveralls.json' 'https://coveralls.io/api/v1/jobs'